export const SET_TIME_FIVE_MINUTES = 'TIME/SET_CHESS-TIME:5:00'; 
export const SET_TIME_TEN_MINUTES = 'TIME/SET_CHESS-TIME:10:00'; 
export const SET_TIME_FIVETEEN_MINUTES = 'TIME/SET_CHESS-TIME:15:00'; 