export const SET_TIME_FIVE_MINUTES = 'TIME/SET_CHESS-TIME:5:00'; 
export const SET_TIME_TEN_MINUTES = 'TIME/SET_CHESS-TIME:10:00'; 
export const SET_TIME_FIVETEEN_MINUTES = 'TIME/SET_CHESS-TIME:15:00'; 

export const WHITE_TO_MOVE = 'MOVE/WHITE_TO_MOVE';
export const BLACK_TO_MOVE = 'MOVE/BLACK_TO_MOVE';