export const SET_TIME_FIVE_MINUTES = 'TIME/SET_CHESS-TIME:5:00'; 
export const SET_TIME_TEN_MINUTES = 'TIME/SET_CHESS-TIME:10:00'; 
export const SET_TIME_FIVETEEN_MINUTES = 'TIME/SET_CHESS-TIME:15:00'; 
export const SET_TIME_THIRTY_MINUTES = 'TIME/SET_CHESS-TIME:30:00';
export const SET_TIME_HOUR = 'TIME/SET_CHESS-TIME:1:00:00';
export const SET_TIME_HOUR_THIRTY = 'TIME/SET_CHESS-TIME:1:30:00';

export const WHITE_TO_MOVE = 'MOVE/WHITE_TO_MOVE';
export const BLACK_TO_MOVE = 'MOVE/BLACK_TO_MOVE';
export const STOP_MOVING = 'MOVE/STOP_MOVING';